# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Roastbook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Roastbook
	pod 'Alamofire', '~> 4.0'
	pod 'AlamofireImage'
end
